### ISSUE TITLE
Last version

### ISSUE THREAD

**Issue by cyrilfr** [vbmithr/ocaml-monocypher#1]
Could you please upgrade to the last version? Last version: [3.0.0](https://github.com/LoupVaillant/Monocypher/tree/3.0.0)

**Comment by vbmithr** [comment]
Yes sure, I was actually trying to do this some days ago and figured out that the update was a bit more difficult than what I thought, but if there is demand for this I'll do it for sure (and maybe an OPAM release).

**Comment by vbmithr** [comment]
Fixed via f2ef9d59d9e716108e32ca88923e3fe90ad402a3
